books = [
    {
        "id": 1,
        "title": "Python Tricks: The Book",
        "author": "Dan Bader",
        "publisher": "Dan Bader",
        "published_date": "2017-10-01",
        "page_count": 302,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Clean Code: A Handbook of Agile Software Craftsmanship",
        "author": "Robert C. Martin",
        "publisher": "Prentice Hall",
        "published_date": "2008-08-01",
        "page_count": 464,
        "language": "English",
    },
    {
        "id": 3,
        "title": "Automate the Boring Stuff with Python",
        "author": "Al Sweigart",
        "publisher": "No Starch Press",
        "published_date": "2015-04-14",
        "page_count": 504,
        "language": "English",
    },
    {
        "id": 4,
        "title": "The Pragmatic Programmer",
        "author": "Andrew Hunt, David Thomas",
        "publisher": "Addison-Wesley",
        "published_date": "1999-10-20",
        "page_count": 352,
        "language": "English",
    },
    {
        "id": 5,
        "title": "You Don't Know JS: Scope & Closures",
        "author": "Kyle Simpson",
        "publisher": "O'Reilly Media",
        "published_date": "2014-12-01",
        "page_count": 98,
        "language": "English",
    },
    {
        "id": 6,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "publisher": "O'Reilly Media",
        "published_date": "2015-08-20",
        "page_count": 792,
        "language": "English",
    },
]
